<?php

namespace smn\lazyc\dbc\Catalog;
use PHPUnit\Framework\TestCase;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-03-08 at 16:47:57.
 */
class CatalogObjectTest extends TestCase {

    /**
     * @var CatalogObject
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() : void {
        $this->object = new CatalogObject('a','a');

        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() : void {
        
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::getType
     * @todo   Implement testGetType().
     */
    public function testGetType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::setName
     * @todo   Implement testSetName().
     */
    public function testSetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::setType
     * @todo   Implement testSetType().
     */
    public function testSetType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::addChild
     * @todo   Implement testAddChild().
     */
    public function testAddChild() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::getChild
     * @todo   Implement testGetChild().
     */
    public function testGetChild() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::getChildren
     * @todo   Implement testGetChildren().
     */
    public function testGetChildren() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::getParent
     * @todo   Implement testGetParent().
     */
    public function testGetParent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::hasChild
     * @todo   Implement testHasChild().
     */
    public function testHasChild() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::hasChildByInstance
     * @todo   Implement testHasChildByInstance().
     */
    public function testHasChildByInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::hasType
     * @todo   Implement testHasType().
     */
    public function testHasType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::removeChild
     * @todo   Implement testRemoveChild().
     */
    public function testRemoveChild() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::removeChildByInstance
     * @todo   Implement testRemoveChildByInstance().
     */
    public function testRemoveChildByInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::setParent
     * @todo   Implement testSetParent().
     */
    public function testSetParent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::getEncoding
     * @todo   Implement testGetEncoding().
     */
    public function testGetEncoding() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::setEncoding
     * @todo   Implement testSetEncoding().
     */
    public function testSetEncoding() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers smn\lazyc\dbc\Catalog\CatalogObject::createCatalogObjectInstance
     * @todo   Implement testCreateCatalogObjectInstance().
     */
    public function testCreateCatalogObjectInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
